### ISSUE TITLE
Restoration filter circuit error

### ISSUE THREAD

**Issue by Grumpy-Mike** [spherical-sound-society/glitch-storm#1]
The capacitor C1 is connected directly to the Arduino's output pin, where as to act as a low pass filter you need it connected to the other side of R1.

**Comment by spherical-sound-society** [comment]
Yeah, that´s true... I will change it. Thanks!!

**Comment by spherical-sound-society** [comment]
Finally Im omitting it, as I think it sounds better without the cap.
